### ISSUE TITLE
Redactar un párrafo de "vision"

### ISSUE THREAD

**Issue by srcolinas** [GWP01/about_us#16]
Esta tarea consiste en editar el [MANIFESTO](https://github.com/GWP01/about_us/blob/master/_ES/MANIFESTO.md) en la sección que muestra la visión del movimiento. Debe ser un párrafo conciso. Está a cargo de @leonfhl  y la idea es que él de el primer comentario al issue con una respuesta, sobre la que todos podremos opinar después.

**Comment by leonfhl** [comment]
Creemos que el aprendizaje debería ser accesible para todos, sin importar dónde naciste, color y, mucho menos, dinero. Creemos en una orientación del aprendizaje con una base en la exploración y creación de conocimiento y no sólo una preparación utilitaria para labores específicas. Creemos en la fuerza de las instituciones abiertas y descentralizadas: sabemos que entre todos podemos crear el mejor sistema de aprendizaje posible y  que las comunidades que trabajan coordinadamente tienen el poder de cambiar las reglas de juego.
