### ISSUE TITLE
Redactar la sección de "pilares"

### ISSUE THREAD

**Issue by srcolinas** [GWP01/about_us#18]
Esta tarea consiste en editar el [MANIFESTO](https://github.com/GWP01/about_us/blob/master/_ES/MANIFESTO.md) en la sección que explica los pilares que rigen el movimiento en todas sus expreciones (filosófico, metodológico y didáctico). Debe ser un párrafo conciso para cada pilar. Está a cargo de @MairaDuqueA  y la idea es que ella de el primer comentario al issue con una respuesta, sobre la que todos podremos opinar después.

**Comment by MairaDuqueA** [comment]
**Pilares** 

Sabemos que cada persona puede construir sus propios conocimientos a partir de las experiencias vividas, los seres con las que comparte, y las herramientas que tiene a su disposición. Para enriquecer todas estas conexiones que hacen posible el aprendizaje, usaremos diferentes plataformas: plataforma con retos de aprendizaje que dibujen rutas de aprendizaje autodirigido; banco de tiempo para compartir habilidades y conocimientos; red de comunicaciones donde las personas puedan encontrarse con otros para crear espacios de aprendizaje juntos; catálogo de expertos que estén dispuestos a acompañar a otros en su proceso de aprendizaje*. (estas plataformas es lo que hablamos la semana pasada de Iván Illich)

A través de las diferentes plataformas que usemos, queremos que cada persona encuentre las rutas para crear sus propios métodos y formas de hacer las cosas; para esto queremos potenciar el desarrollo de habilidades que le permita a los aprendices ser autodidactas, resolver problemas, pensar de manera crítica los retos que enfrentamos hoy en el mundo, y colaborar con otros en la creación de nuevas rutas para el mundo.
* Ser autodidacta: Aprender a aprender
* Resolver problemas: 
* Pensar críticamente: Aquí tengo muchas preguntas. ¿Qué es pensamiento crítico?
* Colaborar con otros: 
Las metodologías que promovemos se inspiran en estos cuatro principios. (aquí hay que escribir unos lineamientos metodológicos por cada principio... ¿cómo esto se traduce en metodología?)

Las experiencias que promovemos son de acceso libre para cualquier persona desde cualquier lugar del mundo, y encuentran en la imagen y las narrativas una forma de conectar a los aprendices....

* Estas cuatro plataformas están inspiradas en las mallas de aprendizaje de la "Sociedad Desescolarizada" de Iván Illich.
